### ISSUE TITLE
bug_リンク付き画像を横長画面で見たときにリンク位置がずれる

### ISSUE THREAD

**Issue by AyaExpTech** [AyaExpTech/FY23-OmiyaFW#81]
### あなたが不具合だと感じている事象は何ですか？

`./int/FindMe.html`閲覧時にリンク位置が右にずれる

### その事象を再現するために、どのような手順をとれば良いと考えられますか？

- 画像内リンクが存在するいずれかのページを開く
- 画面を横に広くなるように調整する
    - 詳細条件不明

### その事象が起こっている部分は、本来どのように動くべきだと考えていますか？

横長画面でも正しい位置にリンクが表示される

### その事象はどの端末で発生しましたか？

- MacBook Air M1

### その事象はどのブラウザで発生しましたか？

- Google Chrome
    - たぶん全ブラウザで起きる

### その事象はどのOSで発生しましたか？

- MacOS sonoma 14.0 beta

### 補足があればここに書いてください。

```css
:is(article, div.sidebar) section .imgContainingLinks {
    width: fit-content;
}
```
たぶんこれを追加すれば治る
